const report = [
  "--- src/App.tsx ---",
  "- Unused state: showDevPanel, setShowDevPanel",
  "- Unused state: expectedRoleForLogin",
  "- Unused function: handleSelectCity",
  "",
  "--- src/components/AITranslatedMessage.tsx ---",
  "- Unused destructured props: originalText, translatedText",
  "",
  "--- src/components/AdminDashboard.tsx ---",
  "- Unused variable: specialists (from useStore)",
  "- Unused state: activeJobsCount",
  "",
  "--- src/components/AgentTestingLab.tsx ---",
  "- Unused state: totalSteps, totalPassedSteps",
  "",
  "--- src/components/CreateOrderModal.tsx ---",
  "- Unused state: setCity",
  "",
  "--- src/components/CustomerDashboard.tsx ---",
  "- Unused prop: t",
  "",
  "--- src/components/CustomerFlow.tsx ---",
  "- Unused state: setSelectedDistrict",
  "- Unused state: searchQuery, setSearchQuery",
  "- Unused state: matchedDispatcher",
  "- Unused function: handleFileUpload",
  "- Unused imports/functions: getCityIconComponent, getRegionMetadata",
  "- Unused prop: name",
  "",
  "--- src/components/LocationSelector.tsx ---",
  "- Unused callback arg: e",
  "",
  "--- src/components/LoginScreen.tsx ---",
  "- Unused prop: onLogout",
  "- Unused state: pendingUser",
  "",
  "--- src/components/MarketplaceServicesManager.tsx ---",
  "- Unused vars: store, idx",
  "",
  "--- src/components/MarketplaceSubscription.tsx ---",
  "- Unused prop/var: currentUser",
  "",
  "--- src/components/OperatorDashboard.tsx ---",
  "- Unused prop/var: activeOperatorId, t, isUploadingPhoto",
  "",
  "--- src/components/OperatorLeadsTerminal.tsx ---",
  "- Unused prop/var: lang, cityFilter, setCityFilter, setBlockedSpecialistIds, uniqueCities",
  "",
  "--- src/components/SpecialistDashboard.tsx ---",
  "- Unused prop/var: onTopupSpecialist, onSelectSpecialist, t",
  "",
  "--- src/components/SpecialistOnboarding.tsx ---",
  "- Unused function: toggleCategory",
  "",
  "--- src/components/SuperAdminDashboard.tsx ---",
  "- Unused variable: specialists (from useStore)",
  "- Unused state: takeoverInput, setTakeoverInput",
  "- Unused variable: totalOperatorsCount",
  "",
  "--- src/components/TerritorialHubsManager.tsx ---",
  "- Unused variable: users",
  "",
  "--- src/lib/agentSimulation/chatVerificationAgent.ts ---",
  "- Unused variable: superAdminUser",
  "",
  "--- src/lib/agentSimulation/userActionDriver.ts ---",
  "- Unused catch arg: err"
];
console.log(report.join('\n'));
