const fs = require('fs');
const ptFile = 'src/locales/pt/translation.json';
const ruFile = 'src/locales/ru/translation.json';

function updateJson(filePath, ns, newKeys) {
  if (!fs.existsSync(filePath)) return;
  const content = fs.readFileSync(filePath, 'utf8');
  const json = JSON.parse(content);
  if (!json[ns]) json[ns] = {};
  Object.assign(json[ns], newKeys);
  fs.writeFileSync(filePath, JSON.stringify(json, null, 2));
}

const pt = {
  "inline_Confirmationrec_1": "Confirmação guardada: Trabalho realizado, pagamento recebido, sem reclamações.",
  "inline_SpecialistDashb_2": "Painel de Especialista",
  "inline_UrgentDispatchB_3": "Quadro de Pedidos Urgentes",
  "inline_MyUnlockedLeads_4": "Os Meus Pedidos Ativos",
  "inline_MyProfile_5": "O Meu Perfil",
  "inline_ServicesSchedul_6": "Serviços e Horários",
  "inline_Notifications_7": "Notificações",
  "inline_SupportHelpdesk_8": "Suporte",
  "inline_UrgentDispatchF_9": "Feed de Pedidos Urgentes",
  "inline_Operatorshaveca_10": "Os operadores pré-calcularam as estimativas. Pague a taxa de lead para desbloquear o contacto. Sem concorrência, quem desbloquear primeiro fica com o cliente.",
  "inline_TheDispatchBoar_11": "O Quadro de Pedidos está atualmente vazio",
  "inline_Wearewaitingfor_12": "Estamos a aguardar novos pedidos urgentes. Assim que forem validados, aparecerão aqui.",
  "inline_EstHours_13": "Horas Est.",
  "inline_Hours_14": "Horas",
  "inline_EstContractValu_15": "Valor Est. Contrato",
  "inline_Published_16": "Publicado:",
  "inline_IamAvailableExp_17": "Estou Disponível",
  "inline_InterestRegiste_18": "Interesse Registado. A aguardar Parceiro Territorial...",
  "inline_Youhavenotunloc_20": "Ainda não desbloqueou nenhum contacto",
  "inline_ActiveLead_22": "Lead Ativo",
  "inline_SECUREDOSSIERAC_23": "DOSSIÊ SEGURO ACEDIDO",
  "inline_WhatsAppClient_24": "WhatsApp Cliente",
  "inline_WhatsAppTP_25": "WhatsApp TP",
  "inline_Workperformedpa_26": "Trabalho realizado, pagamento recebido, sem reclamações ✔",
  "inline_Workperformedpa_27": "Trabalho realizado, pagamento recebido, sem reclamações",
  "inline_JOBADDRESS_28": "ENDEREÇO:",
  "inline_ESTIMATEDVALUE_29": "VALOR ESTIMADO:",
  "inline_VerifiedIssueDe_30": "Descrição Verificada:",
  "inline_File_31": "Ficheiro",
  "inline_ChronologicalCo_32": "Linha do Tempo Cronológica",
  "inline_Notimelinemiles_33": "Ainda sem marcos nesta linha temporal.",
  "inline_TerritoryPartne_34": "Via do Parceiro",
  "inline_DirectCustomerC_35": "Chat Direto Cliente ✔",
  "inline_Nomessagesinthi_36": "Ainda sem mensagens.",
  "inline_SharedDocument_37": "Documento Partilhado",
  "inline_DownloadFile_38": "Descarregar Ficheiro",
  "inline_Typemessageto_39": "Escreva a mensagem para ",
  "inline_Customer_40": "Cliente",
  "inline_TerritoryPartne_41": "Parceiro",
  "inline_Selectanactives_42": "Selecione um dossiê seguro à esquerda para ver a comunicação.",
  "inline_YourInAppNotifi_43": "As suas Notificações",
  "inline_Realtimeautomat_44": "Alertas automáticos e atualizações de suporte em tempo real.",
  "inline_Allnotification_45": "Todas as notificações lidas",
  "inline_Markallread_46": "Marcar todas lidas",
  "inline_Nonotifications_47": "Nenhuma notificação.",
  "inline_SupportHelpdesk_48": "Centro de Suporte",
  "inline_Getassistancere_49": "Obtenha assistência sobre pedidos, reembolsos ou credenciais.",
  "inline_OpenSupportCase_50": "Abrir Ticket de Suporte",
  "inline_NewSupportTicke_51": "Detalhes do Novo Ticket",
  "inline_SupportTicketop_52": "Ticket de suporte aberto. Um administrador responderá brevemente.",
  "inline_ProblemCategory_53": "Categoria do Problema",
  "inline_LeadPurchaseRef_54": "Pedido de Reembolso",
  "inline_ManualBankTopup_55": "Carregamento Manual/Faturação",
  "inline_TechnicalBugUIE_56": "Erro Técnico/Bug UI",
  "inline_CredentialAreaA_57": "Credenciais/Área Geográfica",
  "inline_ShortTicketTitl_58": "Título do Ticket",
  "inline_DetailedExplana_59": "Explicação Detalhada",
  "inline_Cancel_60": "Cancelar",
  "inline_SubmitCase_61": "Submeter Caso",
  "inline_YourSupportTick_62": "Os Seus Tickets",
  "inline_Noactivesupport_63": "Nenhum caso ativo registado.",
  "inline_Ticketnotfound_64": "Ticket não encontrado.",
  "inline_priority_66": "prioridade",
  "inline_AssignedAnalyst_68": "Analista Atribuído:",
  "inline_QueueingforTerr_69": "Na fila para alocação...",
  "inline_SystemCaseEvent_70": "Log de Eventos do Sistema:",
  "inline_Statussynchroni_71": "Estado sincronizado",
  "inline_SendReply_72": "Enviar Resposta",
  "inline_Selectanactives_73": "Selecione um caso ativo à esquerda para ver as respostas.",
  "inline_CreateContracto_74": "Criar Perfil de Prestador",
  "inline_Addanewregional_75": "Adicionar um profissional regional para testar despachos.",
  "inline_FullLegalName_76": "Nome Completo",
  "inline_MobilePhone_77": "Telemóvel",
  "inline_EditSpecialistP_78": "Editar Perfil",
  "inline_Specifyyourcont_79": "Indique os seus contactos, especialidades, região, nível e envie documentos.",
  "inline_ProfilePhoto_80": "Foto de Perfil",
  "inline_Uploaded_81": "Carregado",
  "inline_Nophoto_82": "Sem foto",
  "inline_ChangePhoto_83": "Mudar Foto",
  "inline_UploadPhoto_84": "Enviar Foto",
  "inline_Remove_85": "Remover",
  "inline_ViewFullPhoto_86": "Ver Foto",
  "inline_JPGPNGupto10MBa_87": "Permitidos JPG, PNG até 10 MB.",
  "inline_FullName_88": "Nome Completo",
  "inline_PhoneNumber_89": "Telefone",
  "inline_WhatsAppNumber_90": "Número de WhatsApp",
  "inline_MandatoryforOrd_91": "Obrigatório para Pedidos",
  "inline_UsedbyTerritory_92": "Usado para envio instantâneo via WhatsApp (1 clique).",
  "inline_PrimaryLocation_93": "Área / Localização Principal",
  "inline_MySpecialtiesMa_94": "Especialidades e Níveis",
  "inline_Selectacategory_95": "Selecione as suas categorias e níveis.",
  "inline_Category_96": "Categoria",
  "inline_ChooseCategory_98": "-- Escolher Categoria --",
  "inline_Specialty_99": "Especialidade",
  "inline_ChooseSpecialty_100": "-- Escolher Especialidade --",
  "inline_optionvalueChoo_97": "-- Escolher Especialidade --",
  "inline_Level_101": "Nível",
  "inline_AmateurHobbyist_102": "Amador",
  "inline_Professional_103": "Profissional",
  "inline_ExpertMaster_104": "Mestre / Especialista",
  "inline_MyDeclaredSpeci_105": "As minhas especialidades:",
  "inline_Nospecialtiesad_106": "Nenhuma especialidade adicionada.",
  "inline_SkillsEquipment_107": "Equipamento e Habilidades",
  "inline_LanguagesSpoken_108": "Idiomas",
  "inline_LanguageLevels_109": "Nível de Idiomas:",
  "inline_Basic_110": "Básico",
  "inline_Fluent_111": "Fluente",
  "inline_Native_112": "Nativo",
  "inline_IdentityVerific_113": "Documentos de Identidade",
  "inline_Passport_114": "Passaporte",
  "inline_IDCard_115": "Cartão Cidadão / BI",
  "inline_LoadedActive_116": "Carregado & Ativo",
  "inline_Notuploaded_117": "Não enviado",
  "inline_ViewUploadedFil_118": "Ver Ficheiro",
  "inline_Update_119": "Atualizar",
  "inline_Select_120": "Selecionar",
  "inline_ProfileSavedSub_121": "Perfil Submetido",
  "inline_SavingProfileCh_122": "A Guardar...",
  "inline_SavedSuccessful_123": "Guardado com Sucesso! ✓",
  "inline_SaveProfileChan_124": "Guardar Alterações",
  "inline_StripeSandbox_125": "Simulador Stripe",
  "inline_TerritoryLeadCa_126": "Categoria Territorial",
  "inline_OperatingRegion_127": "Região Geográfica",
  "inline_EstCustomerCont_128": "Valor Est. Cliente",
  "inline_LeadUnlockFee_129": "Taxa de Desbloqueio",
  "inline_StripePaymentSi_130": "Simulador de Pagamentos Stripe",
  "inline_StripeSandbox_131": "Simulador Stripe",
  "inline_ProcessingTrans_133": "A processar...",
  "inline_PaymentSuccessf_134": "Pagamento Bem-sucedido!",
  "inline_GATEWAY_135": "PORTA DE PAGAMENTO",
  "inline_OpenCustomerDos_136": "Abrir Dossiê do Cliente"
};

const ru = {
  "inline_Confirmationrec_1": "Подтверждение: Работы выполнены, оплата получена, претензий нет.",
  "inline_SpecialistDashb_2": "Панель специалиста",
  "inline_UrgentDispatchB_3": "Лента заказов",
  "inline_MyUnlockedLeads_4": "Мои активные заказы",
  "inline_MyProfile_5": "Мой профиль",
  "inline_ServicesSchedul_6": "Услуги и расписание",
  "inline_Notifications_7": "Уведомления",
  "inline_SupportHelpdesk_8": "Поддержка",
  "inline_UrgentDispatchF_9": "Срочные заказы",
  "inline_Operatorshaveca_10": "Операторы уже рассчитали стоимость. Оплатите заказ, чтобы открыть контакты. Заказ получает тот, кто первым оплатит.",
  "inline_TheDispatchBoar_11": "Лента заказов пока пуста",
  "inline_Wearewaitingfor_12": "Ждём новых срочных заявок. Как только клиент создаст заявку, она появится здесь.",
  "inline_EstHours_13": "Прим. Часы",
  "inline_Hours_14": "Часов",
  "inline_EstContractValu_15": "Прим. Стоимость",
  "inline_Published_16": "Опубликовано:",
  "inline_IamAvailableExp_17": "Я готов",
  "inline_InterestRegiste_18": "Отклик отправлен. Ждём ответа партнёра...",
  "inline_Youhavenotunloc_20": "Вы еще не разблокировали ни одного заказа",
  "inline_ActiveLead_22": "Активный заказ",
  "inline_SECUREDOSSIERAC_23": "ДОСТУП К ДОСЬЕ ОТКРЫТ",
  "inline_WhatsAppClient_24": "WhatsApp Клиент",
  "inline_WhatsAppTP_25": "WhatsApp Партнёр",
  "inline_Workperformedpa_26": "Работа выполнена, оплата получена ✔",
  "inline_Workperformedpa_27": "Работа выполнена, оплата получена",
  "inline_JOBADDRESS_28": "АДРЕС:",
  "inline_ESTIMATEDVALUE_29": "ОЦЕНОЧНАЯ СТОИМОСТЬ:",
  "inline_VerifiedIssueDe_30": "Описание проблемы:",
  "inline_File_31": "Файл",
  "inline_ChronologicalCo_32": "Хронология",
  "inline_Notimelinemiles_33": "Событий пока нет.",
  "inline_TerritoryPartne_34": "Канал партнёра",
  "inline_DirectCustomerC_35": "Прямой чат с клиентом ✔",
  "inline_Nomessagesinthi_36": "Сообщений пока нет.",
  "inline_SharedDocument_37": "Общий документ",
  "inline_DownloadFile_38": "Скачать файл",
  "inline_Typemessageto_39": "Написать сообщение для ",
  "inline_Customer_40": "Клиент",
  "inline_TerritoryPartne_41": "Партнёр",
  "inline_Selectanactives_42": "Выберите заказ слева для просмотра чата.",
  "inline_YourInAppNotifi_43": "Ваши уведомления",
  "inline_Realtimeautomat_44": "Автоматические уведомления и обновления от поддержки.",
  "inline_Allnotification_45": "Все прочитаны",
  "inline_Markallread_46": "Пометить как прочитанные",
  "inline_Nonotifications_47": "Уведомлений нет.",
  "inline_SupportHelpdesk_48": "Служба поддержки",
  "inline_Getassistancere_49": "Помощь с заказами, возвратами или профилем.",
  "inline_OpenSupportCase_50": "Создать обращение",
  "inline_NewSupportTicke_51": "Детали обращения",
  "inline_SupportTicketop_52": "Обращение создано. Администратор ответит в ближайшее время.",
  "inline_ProblemCategory_53": "Категория",
  "inline_LeadPurchaseRef_54": "Возврат средств за лид",
  "inline_ManualBankTopup_55": "Пополнение / Оплата",
  "inline_TechnicalBugUIE_56": "Техническая ошибка",
  "inline_CredentialAreaA_57": "Доступы / Регион",
  "inline_ShortTicketTitl_58": "Тема",
  "inline_DetailedExplana_59": "Подробное описание",
  "inline_Cancel_60": "Отмена",
  "inline_SubmitCase_61": "Отправить",
  "inline_YourSupportTick_62": "Ваши обращения",
  "inline_Noactivesupport_63": "Активных обращений нет.",
  "inline_Ticketnotfound_64": "Обращение не найдено.",
  "inline_priority_66": "приоритет",
  "inline_AssignedAnalyst_68": "Назначенный аналитик:",
  "inline_QueueingforTerr_69": "В очереди к партнёру...",
  "inline_SystemCaseEvent_70": "Системный лог:",
  "inline_Statussynchroni_71": "Статус синхронизирован",
  "inline_SendReply_72": "Отправить ответ",
  "inline_Selectanactives_73": "Выберите обращение слева для просмотра.",
  "inline_CreateContracto_74": "Создать профиль",
  "inline_Addanewregional_75": "Добавить нового специалиста.",
  "inline_FullLegalName_76": "Полное имя",
  "inline_MobilePhone_77": "Телефон",
  "inline_EditSpecialistP_78": "Редактировать профиль",
  "inline_Specifyyourcont_79": "Укажите контакты, специальность, регион и документы.",
  "inline_ProfilePhoto_80": "Фото профиля",
  "inline_Uploaded_81": "Загружено",
  "inline_Nophoto_82": "Нет фото",
  "inline_ChangePhoto_83": "Изменить фото",
  "inline_UploadPhoto_84": "Загрузить фото",
  "inline_Remove_85": "Удалить",
  "inline_ViewFullPhoto_86": "Смотреть фото",
  "inline_JPGPNGupto10MBa_87": "JPG, PNG до 10 МБ.",
  "inline_FullName_88": "Полное имя",
  "inline_PhoneNumber_89": "Телефон",
  "inline_WhatsAppNumber_90": "Номер WhatsApp",
  "inline_MandatoryforOrd_91": "Обязательно",
  "inline_UsedbyTerritory_92": "Используется для моментальной связи через WhatsApp.",
  "inline_PrimaryLocation_93": "Основной регион",
  "inline_MySpecialtiesMa_94": "Специальности и навыки",
  "inline_Selectacategory_95": "Выберите категории и ваш уровень.",
  "inline_Category_96": "Категория",
  "inline_ChooseCategory_98": "-- Выбрать категорию --",
  "inline_Specialty_99": "Специальность",
  "inline_ChooseSpecialty_100": "-- Выбрать специальность --",
  "inline_optionvalueChoo_97": "-- Выбрать специальность --",
  "inline_Level_101": "Уровень",
  "inline_AmateurHobbyist_102": "Любитель",
  "inline_Professional_103": "Профессионал",
  "inline_ExpertMaster_104": "Мастер / Эксперт",
  "inline_MyDeclaredSpeci_105": "Мои специальности:",
  "inline_Nospecialtiesad_106": "Специальности не добавлены.",
  "inline_SkillsEquipment_107": "Опыт и оборудование",
  "inline_LanguagesSpoken_108": "Языки",
  "inline_LanguageLevels_109": "Уровень владения:",
  "inline_Basic_110": "Базовый",
  "inline_Fluent_111": "Свободный",
  "inline_Native_112": "Родной",
  "inline_IdentityVerific_113": "Документы",
  "inline_Passport_114": "Паспорт",
  "inline_IDCard_115": "ID Карта",
  "inline_LoadedActive_116": "Загружено",
  "inline_Notuploaded_117": "Не загружено",
  "inline_ViewUploadedFil_118": "Посмотреть файл",
  "inline_Update_119": "Обновить",
  "inline_Select_120": "Выбрать",
  "inline_ProfileSavedSub_121": "Профиль сохранен",
  "inline_SavingProfileCh_122": "Сохранение...",
  "inline_SavedSuccessful_123": "Успешно сохранено! ✓",
  "inline_SaveProfileChan_124": "Сохранить изменения",
  "inline_StripeSandbox_125": "Песочница Stripe",
  "inline_TerritoryLeadCa_126": "Категория заказа",
  "inline_OperatingRegion_127": "Регион",
  "inline_EstCustomerCont_128": "Оценочная стоимость",
  "inline_LeadUnlockFee_129": "Стоимость разблокировки",
  "inline_StripePaymentSi_130": "Эмулятор оплаты Stripe",
  "inline_StripeSandbox_131": "Песочница Stripe",
  "inline_ProcessingTrans_133": "Обработка...",
  "inline_PaymentSuccessf_134": "Оплата успешна!",
  "inline_GATEWAY_135": "ШЛЮЗ",
  "inline_OpenCustomerDos_136": "Открыть досье клиента"
};

updateJson(ptFile, 'spec', pt);
updateJson(ruFile, 'spec', ru);

